### ISSUE TITLE
Don't default to the first person

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/membership_matrix#4]
When I click 'new' it shouldn't default to any person / faction — it's too easy to hit 'save' on that accidentally. Instead it should be a dummy first row that tells me to choose a person and faction.

![screen shot 2016-03-29 at 12 33 45](https://cloud.githubusercontent.com/assets/57483/14106653/9d4f90f0-f5aa-11e5-9d27-cc307a1621a1.png)

**Comment by chrismytton** [comment]
Fixed in https://github.com/everypolitician/membership_matrix/commit/a8d603d2ede97909c98c82ac666fdc68c7923191
